//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Chart_Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_CtrlChartTotalApplicationsWithTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_CtrlChartTotalApplicationsWithTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Chart_Controls.Str_CtrlChartTotalApplicationsWithTime", typeof(Str_CtrlChartTotalApplicationsWithTime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        internal static string allTime {
            get {
                return ResourceManager.GetString("allTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Applications Over Time.
        /// </summary>
        internal static string chartTitle {
            get {
                return ResourceManager.GetString("chartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total applications.
        /// </summary>
        internal static string inTotal {
            get {
                return ResourceManager.GetString("inTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New International License.
        /// </summary>
        internal static string newInterLicense {
            get {
                return ResourceManager.GetString("newInterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Local License.
        /// </summary>
        internal static string newLocalLicense {
            get {
                return ResourceManager.GetString("newLocalLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Total.
        /// </summary>
        internal static string overallTotal {
            get {
                return ResourceManager.GetString("overallTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Detained License.
        /// </summary>
        internal static string releaseDetainedLicense {
            get {
                return ResourceManager.GetString("releaseDetainedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew License.
        /// </summary>
        internal static string renewLicense {
            get {
                return ResourceManager.GetString("renewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Damaged License.
        /// </summary>
        internal static string replaceDamagedLicense {
            get {
                return ResourceManager.GetString("replaceDamagedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Lost License.
        /// </summary>
        internal static string replaceLostLicense {
            get {
                return ResourceManager.GetString("replaceLostLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake Failed Test.
        /// </summary>
        internal static string retakeFailedTest {
            get {
                return ResourceManager.GetString("retakeFailedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Applications.
        /// </summary>
        internal static string totalApplications {
            get {
                return ResourceManager.GetString("totalApplications", resourceCulture);
            }
        }
    }
}
