//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Chart_Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_CtrlChartLicenseDetainFineFees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_CtrlChartLicenseDetainFineFees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Chart_Controls.Str_CtrlChartLicenseDetainFineFees", typeof(Str_CtrlChartLicenseDetainFineFees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Detention Fine Fees.
        /// </summary>
        internal static string chartTitle {
            get {
                return ResourceManager.GetString("chartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string fees {
            get {
                return ResourceManager.GetString("fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released Licenses.
        /// </summary>
        internal static string releasedLicenses {
            get {
                return ResourceManager.GetString("releasedLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those are the fees that are paid and may represent revenue.
        ///They are grouped by the month on which they were paid..
        /// </summary>
        internal static string releasedLicensesLegendToolTip {
            get {
                return ResourceManager.GetString("releasedLicensesLegendToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summation.
        /// </summary>
        internal static string summation {
            get {
                return ResourceManager.GetString("summation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total fees.
        /// </summary>
        internal static string totalFees {
            get {
                return ResourceManager.GetString("totalFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased Licenses.
        /// </summary>
        internal static string unreleasedLicenses {
            get {
                return ResourceManager.GetString("unreleasedLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those are the fees that are registered but not yet paid.
        ///They are grouped by the month on which they were registered..
        /// </summary>
        internal static string unreleasedLicensesLegendToolTip {
            get {
                return ResourceManager.GetString("unreleasedLicensesLegendToolTip", resourceCulture);
            }
        }
    }
}
