//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Chart_Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_CtrlSystemWideRevenue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_CtrlSystemWideRevenue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Chart_Controls.Str_CtrlSystemWideRevenue", typeof(Str_CtrlSystemWideRevenue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string dateTime {
            get {
                return ResourceManager.GetString("dateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string filter_application {
            get {
                return ResourceManager.GetString("filter_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Fees Payment.
        /// </summary>
        internal static string filter_detentionFinePayment {
            get {
                return ResourceManager.GetString("filter_detentionFinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Local License (First Time).
        /// </summary>
        internal static string filter_localLicenseIssuance {
            get {
                return ResourceManager.GetString("filter_localLicenseIssuance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Appointment.
        /// </summary>
        internal static string filter_testAppointment {
            get {
                return ResourceManager.GetString("filter_testAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered By.
        /// </summary>
        internal static string registeredBy {
            get {
                return ResourceManager.GetString("registeredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Source.
        /// </summary>
        internal static string revenueSource {
            get {
                return ResourceManager.GetString("revenueSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Type.
        /// </summary>
        internal static string sourceType {
            get {
                return ResourceManager.GetString("sourceType", resourceCulture);
            }
        }
    }
}
