//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Chart_Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_CtrlChartTestTypesPassRates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_CtrlChartTestTypesPassRates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Chart_Controls.Str_CtrlChartTestTypesPassRates", typeof(Str_CtrlChartTestTypesPassRates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempts on average.
        /// </summary>
        internal static string attemptsOnAvg {
            get {
                return ResourceManager.GetString("attemptsOnAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Attempts.
        /// </summary>
        internal static string avgAttempts {
            get {
                return ResourceManager.GetString("avgAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Driving Test Attempts.
        /// </summary>
        internal static string avgDrivingTestAttempts {
            get {
                return ResourceManager.GetString("avgDrivingTestAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Vision Test Attempts.
        /// </summary>
        internal static string avgVisionTestAttempts {
            get {
                return ResourceManager.GetString("avgVisionTestAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Written Test Attempts.
        /// </summary>
        internal static string avgWrittenTestAttempts {
            get {
                return ResourceManager.GetString("avgWrittenTestAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Attempts To Pass (Dashed Line).
        /// </summary>
        internal static string chartTitle_avgAttempts {
            get {
                return ResourceManager.GetString("chartTitle_avgAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results Rates (Solid Line).
        /// </summary>
        internal static string chartTitle_testPassRates {
            get {
                return ResourceManager.GetString("chartTitle_testPassRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Tests.
        /// </summary>
        internal static string drivingTests {
            get {
                return ResourceManager.GetString("drivingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Rate.
        /// </summary>
        internal static string passRate {
            get {
                return ResourceManager.GetString("passRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Selected Month-.
        /// </summary>
        internal static string selectedMonth {
            get {
                return ResourceManager.GetString("selectedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        internal static string testResult {
            get {
                return ResourceManager.GetString("testResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Average Attempts.
        /// </summary>
        internal static string totalAvgAttempts {
            get {
                return ResourceManager.GetString("totalAvgAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tests.
        /// </summary>
        internal static string totalTests {
            get {
                return ResourceManager.GetString("totalTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Tests.
        /// </summary>
        internal static string visionTests {
            get {
                return ResourceManager.GetString("visionTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Tests.
        /// </summary>
        internal static string writtenTests {
            get {
                return ResourceManager.GetString("writtenTests", resourceCulture);
            }
        }
    }
}
