//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmDetainLicense {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmDetainLicense() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmDetainLicense", typeof(Str_FrmDetainLicense).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the detention data.
        ///Please try again..
        /// </summary>
        internal static string detainFailed {
            get {
                return ResourceManager.GetString("detainFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to detain this license?.
        /// </summary>
        internal static string detainLicenseConfirm {
            get {
                return ResourceManager.GetString("detainLicenseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detain operation succeeded with ID = .
        /// </summary>
        internal static string detainSucceededWithID {
            get {
                return ResourceManager.GetString("detainSucceededWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected license is already detained.
        ///Choose another license..
        /// </summary>
        internal static string selectedLicenseAlreadyDetained {
            get {
                return ResourceManager.GetString("selectedLicenseAlreadyDetained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected license is not active.
        ///You can only detain active licenses..
        /// </summary>
        internal static string selectedLicenseNotActive {
            get {
                return ResourceManager.GetString("selectedLicenseNotActive", resourceCulture);
            }
        }
    }
}
