//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmIssueNewInternationalLicense {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmIssueNewInternationalLicense() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmIssueNewInternationalLicense", typeof(Str_FrmIssueNewInternationalLicense).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists an active international license attached to this local license..
        /// </summary>
        internal static string activeInterLicenseAlreadyExists {
            get {
                return ResourceManager.GetString("activeInterLicenseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that this driver already owns an active international license
        ///but attached to a different local license that has already expired.
        ///Issuing this license will deactivate the existing one and replace it..
        /// </summary>
        internal static string anActiveInterLicenseExist_LocalInvactive {
            get {
                return ResourceManager.GetString("anActiveInterLicenseExist_LocalInvactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only issue an international license of kind &quot;Class 3 - Ordinary Driving License&quot;..
        /// </summary>
        internal static string canOnlyIssueClass3 {
            get {
                return ResourceManager.GetString("canOnlyIssueClass3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified license is not active; You cannot issue a new international license based on it..
        /// </summary>
        internal static string chosenLicenseInvactive {
            get {
                return ResourceManager.GetString("chosenLicenseInvactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to issue this license?.
        /// </summary>
        internal static string issueLicenseConfirm {
            get {
                return ResourceManager.GetString("issueLicenseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a local license with this ID.
        ///Please try again..
        /// </summary>
        internal static string localLicenseNotFound {
            get {
                return ResourceManager.GetString("localLicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International License saved successfully with ID = .
        /// </summary>
        internal static string savedSuccessfullyWithID {
            get {
                return ResourceManager.GetString("savedSuccessfullyWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the international license.
        ///Please try again..
        /// </summary>
        internal static string savingLicenseFailed {
            get {
                return ResourceManager.GetString("savingLicenseFailed", resourceCulture);
            }
        }
    }
}
