//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmAddEditUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmAddEditUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmAddEditUser", typeof(Str_FrmAddEditUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to deactivate the logged-in user.
        ///If you proceed, you will immediately get logged-out from the system.
        ///Proceed?.
        /// </summary>
        internal static string attemptingDeactivatingActiveUser {
            get {
                return ResourceManager.GetString("attemptingDeactivatingActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input must match with the &quot;Password&quot; field..
        /// </summary>
        internal static string invalidConfirmPasswordInput {
            get {
                return ResourceManager.GetString("invalidConfirmPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person is already registered as a user in the system.
        ///Choose another one..
        /// </summary>
        internal static string personAlreadyRegisteredAsUser {
            get {
                return ResourceManager.GetString("personAlreadyRegisteredAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That person doesn&apos;t exist in the system..
        /// </summary>
        internal static string personNotExist {
            get {
                return ResourceManager.GetString("personNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        internal static string updateUser {
            get {
                return ResourceManager.GetString("updateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User&apos;s Info.
        /// </summary>
        internal static string updateUserInfo {
            get {
                return ResourceManager.GetString("updateUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already chosen by another user..
        /// </summary>
        internal static string usernameAlreadyChosen {
            get {
                return ResourceManager.GetString("usernameAlreadyChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully with ID = .
        /// </summary>
        internal static string userSavedSuccessfullyWithID {
            get {
                return ResourceManager.GetString("userSavedSuccessfullyWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the user&apos;s info.
        ///Please try again..
        /// </summary>
        internal static string userSaveFailed {
            get {
                return ResourceManager.GetString("userSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first choose a person..
        /// </summary>
        internal static string youMustFirstChoosePerson {
            get {
                return ResourceManager.GetString("youMustFirstChoosePerson", resourceCulture);
            }
        }
    }
}
