//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmManageLicenseClasses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmManageLicenseClasses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmManageLicenseClasses", typeof(Str_FrmManageLicenseClasses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Fees.
        /// </summary>
        internal static string classFees {
            get {
                return ResourceManager.GetString("classFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string className {
            get {
                return ResourceManager.GetString("className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Length.
        /// </summary>
        internal static string defaultValidityLength {
            get {
                return ResourceManager.GetString("defaultValidityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The age cannot be greater than 100.
        /// </summary>
        internal static string invalidAgeInput {
            get {
                return ResourceManager.GetString("invalidAgeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Classes.
        /// </summary>
        internal static string licenseClasses {
            get {
                return ResourceManager.GetString("licenseClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Allowed Age.
        /// </summary>
        internal static string minimumAllowedAge {
            get {
                return ResourceManager.GetString("minimumAllowedAge", resourceCulture);
            }
        }
    }
}
