//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmAddEditLocalDrivingLicenseApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmAddEditLocalDrivingLicenseApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmAddEditLocalDrivingLicenseApp", typeof(Str_FrmAddEditLocalDrivingLicenseApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists an open application with this license class attached to this person..
        /// </summary>
        internal static string anOpenApplicationExistsForPerson {
            get {
                return ResourceManager.GetString("anOpenApplicationExistsForPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application saved successfully with ID = .
        /// </summary>
        internal static string applicationSavedSuccessfullyWithID {
            get {
                return ResourceManager.GetString("applicationSavedSuccessfullyWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application saved successfully..
        /// </summary>
        internal static string applicationSavedSucessfully {
            get {
                return ResourceManager.GetString("applicationSavedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person you chose no longer exists in the database!
        ///Choose another one..
        /// </summary>
        internal static string chosenPersonNoLongerExists {
            get {
                return ResourceManager.GetString("chosenPersonNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person is younger than the minimum allowed age for this license class.
        ///Chose another one..
        /// </summary>
        internal static string invalidChosenPersonAge {
            get {
                return ResourceManager.GetString("invalidChosenPersonAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person already have an active license of this license class..
        /// </summary>
        internal static string personAlreadyHaveActiveLicense {
            get {
                return ResourceManager.GetString("personAlreadyHaveActiveLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Local Driving License Application.
        /// </summary>
        internal static string updateLDLApp {
            get {
                return ResourceManager.GetString("updateLDLApp", resourceCulture);
            }
        }
    }
}
