//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmUserPermissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmUserPermissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmUserPermissions", typeof(Str_FrmUserPermissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate/Deactivate User.
        /// </summary>
        internal static string activate_deactivateUser {
            get {
                return ResourceManager.GetString("activate_deactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Person.
        /// </summary>
        internal static string addNewPerson {
            get {
                return ResourceManager.GetString("addNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string addNewUser {
            get {
                return ResourceManager.GetString("addNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Types.
        /// </summary>
        internal static string appTypes {
            get {
                return ResourceManager.GetString("appTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to →.
        /// </summary>
        internal static string arrow {
            get {
                return ResourceManager.GetString("arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Application.
        /// </summary>
        internal static string cancelApp {
            get {
                return ResourceManager.GetString("cancelApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Color Mode.
        /// </summary>
        internal static string changeColorMode {
            get {
                return ResourceManager.GetString("changeColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Password.
        /// </summary>
        internal static string changeUserPassword {
            get {
                return ResourceManager.GetString("changeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Permissions.
        /// </summary>
        internal static string changeUserPermissions {
            get {
                return ResourceManager.GetString("changeUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Appointment.
        /// </summary>
        internal static string createNewAppoint {
            get {
                return ResourceManager.GetString("createNewAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New International License Application -- Issue New International License.
        /// </summary>
        internal static string createNewInterLicenseApp {
            get {
                return ResourceManager.GetString("createNewInterLicenseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Local License Application.
        /// </summary>
        internal static string createNewLocalLicenseApp {
            get {
                return ResourceManager.GetString("createNewLocalLicenseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Theme (Branch/From Scratch).
        /// </summary>
        internal static string createNewTheme {
            get {
                return ResourceManager.GetString("createNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Application.
        /// </summary>
        internal static string deleteApp {
            get {
                return ResourceManager.GetString("deleteApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person.
        /// </summary>
        internal static string deletePerson {
            get {
                return ResourceManager.GetString("deletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Theme.
        /// </summary>
        internal static string deleteTheme {
            get {
                return ResourceManager.GetString("deleteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string deleteUser {
            get {
                return ResourceManager.GetString("deleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detain License.
        /// </summary>
        internal static string detainLicense {
            get {
                return ResourceManager.GetString("detainLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Application Info.
        /// </summary>
        internal static string editAppInfo {
            get {
                return ResourceManager.GetString("editAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Personal Info.
        /// </summary>
        internal static string editPersonalInfo {
            get {
                return ResourceManager.GetString("editPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Theme Values.
        /// </summary>
        internal static string editThemeValues {
            get {
                return ResourceManager.GetString("editThemeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Username.
        /// </summary>
        internal static string editUsername {
            get {
                return ResourceManager.GetString("editUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Appointments Data.
        /// </summary>
        internal static string exportAppointsData {
            get {
                return ResourceManager.GetString("exportAppointsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        internal static string exportData {
            get {
                return ResourceManager.GetString("exportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Detained Licenses Data.
        /// </summary>
        internal static string exportDetainedLicensesData {
            get {
                return ResourceManager.GetString("exportDetainedLicensesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Drivers Data.
        /// </summary>
        internal static string exportDriversData {
            get {
                return ResourceManager.GetString("exportDriversData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export International License Applications Data.
        /// </summary>
        internal static string exportInterLicenseAppData {
            get {
                return ResourceManager.GetString("exportInterLicenseAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export International Licenses Data.
        /// </summary>
        internal static string exportInterLicensesData {
            get {
                return ResourceManager.GetString("exportInterLicensesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Local License Applications Data.
        /// </summary>
        internal static string exportLocalLicenseAppsData {
            get {
                return ResourceManager.GetString("exportLocalLicenseAppsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Local Licenses Data.
        /// </summary>
        internal static string exportLocalLicensesData {
            get {
                return ResourceManager.GetString("exportLocalLicensesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export People Data.
        /// </summary>
        internal static string exportPeopleData {
            get {
                return ResourceManager.GetString("exportPeopleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Users Data.
        /// </summary>
        internal static string exportUsersData {
            get {
                return ResourceManager.GetString("exportUsersData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Access.
        /// </summary>
        internal static string fullAccess {
            get {
                return ResourceManager.GetString("fullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue License Replacement.
        /// </summary>
        internal static string issueLicenseReplacement {
            get {
                return ResourceManager.GetString("issueLicenseReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Local License (First Time).
        /// </summary>
        internal static string issueLocalLicenseFirstTime {
            get {
                return ResourceManager.GetString("issueLocalLicenseFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Classes.
        /// </summary>
        internal static string licenseClasses {
            get {
                return ResourceManager.GetString("licenseClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Access.
        /// </summary>
        internal static string noAccess {
            get {
                return ResourceManager.GetString("noAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Call.
        /// </summary>
        internal static string phoneCall {
            get {
                return ResourceManager.GetString("phoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Detained License.
        /// </summary>
        internal static string releaseDetainedLicense {
            get {
                return ResourceManager.GetString("releaseDetainedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Theme.
        /// </summary>
        internal static string renameTheme {
            get {
                return ResourceManager.GetString("renameTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew License.
        /// </summary>
        internal static string renewLicense {
            get {
                return ResourceManager.GetString("renewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Appointments.
        /// </summary>
        internal static string seeAllAppoints {
            get {
                return ResourceManager.GetString("seeAllAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Drivers.
        /// </summary>
        internal static string seeAllDrivers {
            get {
                return ResourceManager.GetString("seeAllDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All International License Applications.
        /// </summary>
        internal static string seeAllInterLicenseApps {
            get {
                return ResourceManager.GetString("seeAllInterLicenseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Local License Applications.
        /// </summary>
        internal static string seeAllLocalLicenseApps {
            get {
                return ResourceManager.GetString("seeAllLocalLicenseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All People.
        /// </summary>
        internal static string seeAllPeople {
            get {
                return ResourceManager.GetString("seeAllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Users.
        /// </summary>
        internal static string seeAllUsers {
            get {
                return ResourceManager.GetString("seeAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Driver Driving Tests History.
        /// </summary>
        internal static string seeDriverDrivingTestsHistory {
            get {
                return ResourceManager.GetString("seeDriverDrivingTestsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Driver International Licenses History.
        /// </summary>
        internal static string seeDriverInterLicensesHistory {
            get {
                return ResourceManager.GetString("seeDriverInterLicensesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Driver Local Licenses History.
        /// </summary>
        internal static string seeDriverLocalLicensesHistory {
            get {
                return ResourceManager.GetString("seeDriverLocalLicensesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Driver Vision Tests History.
        /// </summary>
        internal static string seeDriversVisionTestsHistory {
            get {
                return ResourceManager.GetString("seeDriversVisionTestsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Driver Written Tests History.
        /// </summary>
        internal static string seeDriverWrittenTestsHistory {
            get {
                return ResourceManager.GetString("seeDriverWrittenTestsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Personal Info Cards.
        /// </summary>
        internal static string seePersonalInfoCards {
            get {
                return ResourceManager.GetString("seePersonalInfoCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string sendEmail {
            get {
                return ResourceManager.GetString("sendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Full International License Info.
        /// </summary>
        internal static string showFullInterLicenseInfo {
            get {
                return ResourceManager.GetString("showFullInterLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Full Local License Info.
        /// </summary>
        internal static string showFullLocalLicenseInfo {
            get {
                return ResourceManager.GetString("showFullLocalLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System-Wide Revenue.
        /// </summary>
        internal static string systemWideRevenue {
            get {
                return ResourceManager.GetString("systemWideRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results Rates -- Average Attempts To Pass.
        /// </summary>
        internal static string testResultsRates_avgAttemptsToPass {
            get {
                return ResourceManager.GetString("testResultsRates_avgAttemptsToPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Types.
        /// </summary>
        internal static string testTypes {
            get {
                return ResourceManager.GetString("testTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Appointment Info.
        /// </summary>
        internal static string updateAppointInfo {
            get {
                return ResourceManager.GetString("updateAppointInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        internal static string updateData {
            get {
                return ResourceManager.GetString("updateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Data.
        /// </summary>
        internal static string viewAllData {
            get {
                return ResourceManager.GetString("viewAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Detained Licenses.
        /// </summary>
        internal static string viewAllDetainedLicenses {
            get {
                return ResourceManager.GetString("viewAllDetainedLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All International Licenses.
        /// </summary>
        internal static string viewAllInterLicenses {
            get {
                return ResourceManager.GetString("viewAllInterLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Local Licenses.
        /// </summary>
        internal static string viewAllLocalLicenses {
            get {
                return ResourceManager.GetString("viewAllLocalLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full Application Details.
        /// </summary>
        internal static string viewFullAppDetails {
            get {
                return ResourceManager.GetString("viewFullAppDetails", resourceCulture);
            }
        }
    }
}
