//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Chart_Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_CtrlChartRevenueByLicenseClass {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_CtrlChartRevenueByLicenseClass() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Chart_Controls.Str_CtrlChartRevenueByLicenseClass", typeof(Str_CtrlChartRevenueByLicenseClass).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue By License Class.
        /// </summary>
        internal static string chartTitle {
            get {
                return ResourceManager.GetString("chartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1 - Small Motorcycles.
        /// </summary>
        internal static string class1 {
            get {
                return ResourceManager.GetString("class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2 - Heavy Motorcycles.
        /// </summary>
        internal static string class2 {
            get {
                return ResourceManager.GetString("class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3 - Ordinary.
        /// </summary>
        internal static string class3 {
            get {
                return ResourceManager.GetString("class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C4 - Commerical.
        /// </summary>
        internal static string class4 {
            get {
                return ResourceManager.GetString("class4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C5 - Agricultural.
        /// </summary>
        internal static string class5 {
            get {
                return ResourceManager.GetString("class5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C6 - Small &amp; Medium Buses.
        /// </summary>
        internal static string class6 {
            get {
                return ResourceManager.GetString("class6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C7 - Truck &amp; Heavy Vehicles.
        /// </summary>
        internal static string class7 {
            get {
                return ResourceManager.GetString("class7", resourceCulture);
            }
        }
    }
}
