//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Chart_Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_CtrlChartTestAppointmentsLoad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_CtrlChartTestAppointmentsLoad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Chart_Controls.Str_CtrlChartTestAppointmentsLoad", typeof(Str_CtrlChartTestAppointmentsLoad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint. Date.
        /// </summary>
        internal static string appointmentDate {
            get {
                return ResourceManager.GetString("appointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string appointments {
            get {
                return ResourceManager.GetString("appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Appointments Load.
        /// </summary>
        internal static string chartTitle {
            get {
                return ResourceManager.GetString("chartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Test.
        /// </summary>
        internal static string drivingTest {
            get {
                return ResourceManager.GetString("drivingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Test Appointments.
        /// </summary>
        internal static string drivingTestAppoints {
            get {
                return ResourceManager.GetString("drivingTestAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.Appoint. ID.
        /// </summary>
        internal static string testAppointmentID {
            get {
                return ResourceManager.GetString("testAppointmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Appointments.
        /// </summary>
        internal static string totalAppointments {
            get {
                return ResourceManager.GetString("totalAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Test.
        /// </summary>
        internal static string visionTest {
            get {
                return ResourceManager.GetString("visionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Test Appointments.
        /// </summary>
        internal static string visionTestAppoints {
            get {
                return ResourceManager.GetString("visionTestAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Test.
        /// </summary>
        internal static string writtenTest {
            get {
                return ResourceManager.GetString("writtenTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Test Appointments.
        /// </summary>
        internal static string writtenTestAppoints {
            get {
                return ResourceManager.GetString("writtenTestAppoints", resourceCulture);
            }
        }
    }
}
