//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmReport", typeof(Str_FrmReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least one option from the checkbox list..
        /// </summary>
        internal static string chooseOneOptionAtLeast {
            get {
                return ResourceManager.GetString("chooseOneOptionAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while exporting the file.
        ///Please try again..
        /// </summary>
        internal static string exportFileFailed {
            get {
                return ResourceManager.GetString("exportFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;End Date&quot; value must be equal to or greater than &quot;Start Date&quot;..
        /// </summary>
        internal static string invalidDateRange {
            get {
                return ResourceManager.GetString("invalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review your input in the &quot;Document Export Settings&quot; section then try again..
        /// </summary>
        internal static string invalidExportSettings {
            get {
                return ResourceManager.GetString("invalidExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong attempting to print the document.
        ///Please try again..
        /// </summary>
        internal static string printDocumentFailed {
            get {
                return ResourceManager.GetString("printDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected person is not a registered driver on the system.
        ///Choose another one..
        /// </summary>
        internal static string selectedPersonNotDriver {
            get {
                return ResourceManager.GetString("selectedPersonNotDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected person is not a registered user on the system.
        ///Choose another one..
        /// </summary>
        internal static string selectedPersonNotUser {
            get {
                return ResourceManager.GetString("selectedPersonNotUser", resourceCulture);
            }
        }
    }
}
