//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmSettings", typeof(Str_FrmSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Mode:.
        /// </summary>
        internal static string colorMode {
            get {
                return ResourceManager.GetString("colorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Create New Theme&gt;.
        /// </summary>
        internal static string createNewTheme {
            get {
                return ResourceManager.GetString("createNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about deleting this theme?
        ///You cannot undo this action!.
        /// </summary>
        internal static string deletingConfirm {
            get {
                return ResourceManager.GetString("deletingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Theme.
        /// </summary>
        internal static string newTheme {
            get {
                return ResourceManager.GetString("newTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Theme.
        /// </summary>
        internal static string renameTheme {
            get {
                return ResourceManager.GetString("renameTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about saving?
        ///You cannot undo this action!.
        /// </summary>
        internal static string savingConfirm {
            get {
                return ResourceManager.GetString("savingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme deleted successfully..
        /// </summary>
        internal static string themeDeletedSuccessfully {
            get {
                return ResourceManager.GetString("themeDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken by another theme..
        /// </summary>
        internal static string themeNameAlreadyTaken {
            get {
                return ResourceManager.GetString("themeNameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new theme has been saved successfully with ID = .
        /// </summary>
        internal static string themeSavedSuccessfullyWithID {
            get {
                return ResourceManager.GetString("themeSavedSuccessfullyWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving the new theme.
        ///Please try again..
        /// </summary>
        internal static string themeSaveFailed {
            get {
                return ResourceManager.GetString("themeSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be some unsaved changes to the selected theme.
        ///Would you like the save them before applying the theme?.
        /// </summary>
        internal static string unsavedChangesExist {
            get {
                return ResourceManager.GetString("unsavedChangesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not exceed 360..
        /// </summary>
        internal static string valueNotExceed360 {
            get {
                return ResourceManager.GetString("valueNotExceed360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now style it however you like..
        /// </summary>
        internal static string youCanStyleNow {
            get {
                return ResourceManager.GetString("youCanStyleNow", resourceCulture);
            }
        }
    }
}
