//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_FrmTestAppointments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_FrmTestAppointments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Forms.Str_FrmTestAppointments", typeof(Str_FrmTestAppointments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists an open appointment for this test. You cannot schedule a new appointment..
        /// </summary>
        internal static string anOpenAppointmentAlreadyExists {
            get {
                return ResourceManager.GetString("anOpenAppointmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applicant has already passed this test. You cannot schedule a new appointment..
        /// </summary>
        internal static string applicantAlreadyPassedTest {
            get {
                return ResourceManager.GetString("applicantAlreadyPassedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        internal static string appointmentDate {
            get {
                return ResourceManager.GetString("appointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment ID.
        /// </summary>
        internal static string appointmentID {
            get {
                return ResourceManager.GetString("appointmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment State.
        /// </summary>
        internal static string isLocked {
            get {
                return ResourceManager.GetString("isLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Test Results.
        /// </summary>
        internal static string showTestResults {
            get {
                return ResourceManager.GetString("showTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Test Appointments.
        /// </summary>
        internal static string streetTestAppointments {
            get {
                return ResourceManager.GetString("streetTestAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Test.
        /// </summary>
        internal static string takeTest {
            get {
                return ResourceManager.GetString("takeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Appointments.
        /// </summary>
        internal static string testAppointments {
            get {
                return ResourceManager.GetString("testAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid Fees.
        /// </summary>
        internal static string totalPaidFees {
            get {
                return ResourceManager.GetString("totalPaidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Test Appointments.
        /// </summary>
        internal static string visionTestAppointments {
            get {
                return ResourceManager.GetString("visionTestAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Test Appointments.
        /// </summary>
        internal static string writtenTestAppointments {
            get {
                return ResourceManager.GetString("writtenTestAppointments", resourceCulture);
            }
        }
    }
}
