//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Layouts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_LayoutManageLocalDrivingLicenseApps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_LayoutManageLocalDrivingLicenseApps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Layouts.Str_LayoutManageLocalDrivingLicenseApps", typeof(Str_LayoutManageLocalDrivingLicenseApps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the underlaying applicant info.
        ///Please check your database..
        /// </summary>
        internal static string applicantInfoNotFound {
            get {
                return ResourceManager.GetString("applicantInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this application?
        ///You cannot undo this action!.
        /// </summary>
        internal static string applicationCancelConfirm {
            get {
                return ResourceManager.GetString("applicationCancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Date.
        /// </summary>
        internal static string applicationDate {
            get {
                return ResourceManager.GetString("applicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this application?
        ///You cannot undo this action!.
        /// </summary>
        internal static string applicationDeleteConfirm {
            get {
                return ResourceManager.GetString("applicationDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application deleted successfully..
        /// </summary>
        internal static string applicationDeletedSuccessfully {
            get {
                return ResourceManager.GetString("applicationDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done successfully..
        /// </summary>
        internal static string doneSuccessfully {
            get {
                return ResourceManager.GetString("doneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Class.
        /// </summary>
        internal static string licenseClass {
            get {
                return ResourceManager.GetString("licenseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.D.L.App. ID.
        /// </summary>
        internal static string localDrivingLicenseAppID {
            get {
                return ResourceManager.GetString("localDrivingLicenseAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Driving License Applications.
        /// </summary>
        internal static string localDrivingLicenseApps {
            get {
                return ResourceManager.GetString("localDrivingLicenseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Test Passed.
        /// </summary>
        internal static string numOfTestPassed {
            get {
                return ResourceManager.GetString("numOfTestPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
