//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD_Business.Report_Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_DriverProfileReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_DriverProfileReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD_Business.Report_Strings.Str_DriverProfileReport", typeof(Str_DriverProfileReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active International Licenses.
        /// </summary>
        internal static string cap_activeInterLicenses {
            get {
                return ResourceManager.GetString("cap_activeInterLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Local Licenses.
        /// </summary>
        internal static string cap_activeLocalLicenses {
            get {
                return ResourceManager.GetString("cap_activeLocalLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive/Expired International Licenses.
        /// </summary>
        internal static string cap_inactiveInterLicenses {
            get {
                return ResourceManager.GetString("cap_inactiveInterLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive/Expired Local Licenses.
        /// </summary>
        internal static string cap_inactiveLocalLicenses {
            get {
                return ResourceManager.GetString("cap_inactiveLocalLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string cap_personalInfo {
            get {
                return ResourceManager.GetString("cap_personalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string field_dateCreated {
            get {
                return ResourceManager.GetString("field_dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver ID.
        /// </summary>
        internal static string field_driverID {
            get {
                return ResourceManager.GetString("field_driverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Licenses.
        /// </summary>
        internal static string h_activeLicenses {
            get {
                return ResourceManager.GetString("h_activeLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Licenses (International).
        /// </summary>
        internal static string h_activeLicenses_inter {
            get {
                return ResourceManager.GetString("h_activeLicenses_inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Licenses (Local).
        /// </summary>
        internal static string h_activeLicenses_local {
            get {
                return ResourceManager.GetString("h_activeLicenses_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Info.
        /// </summary>
        internal static string h_driverInfo {
            get {
                return ResourceManager.GetString("h_driverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive/Expired Licenses.
        /// </summary>
        internal static string h_inactiveLicenses {
            get {
                return ResourceManager.GetString("h_inactiveLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive/Expired Licenses (International).
        /// </summary>
        internal static string h_inactiveLicenses_inter {
            get {
                return ResourceManager.GetString("h_inactiveLicenses_inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive/Expired Licenses (Local).
        /// </summary>
        internal static string h_inactiveLicenses_local {
            get {
                return ResourceManager.GetString("h_inactiveLicenses_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A report documenting the profile of a driver of the ID .
        /// </summary>
        internal static string reportSubject_1 {
            get {
                return ResourceManager.GetString("reportSubject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Profile Report.
        /// </summary>
        internal static string reportTitle {
            get {
                return ResourceManager.GetString("reportTitle", resourceCulture);
            }
        }
    }
}
