//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color BaseBackColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseBackColor"]));
            }
            set {
                this["BaseBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color BaseForeColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseForeColor"]));
            }
            set {
                this["BaseForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 0, 0")]
        public global::System.Drawing.Color AccentForeColor {
            get {
                return ((global::System.Drawing.Color)(this["AccentForeColor"]));
            }
            set {
                this["AccentForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color BaseLinkColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseLinkColor"]));
            }
            set {
                this["BaseLinkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color InactiveForeColor {
            get {
                return ((global::System.Drawing.Color)(this["InactiveForeColor"]));
            }
            set {
                this["InactiveForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color StrongForeColor {
            get {
                return ((global::System.Drawing.Color)(this["StrongForeColor"]));
            }
            set {
                this["StrongForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241, 245, 249")]
        public global::System.Drawing.Color MenuStripBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripBackColor"]));
            }
            set {
                this["MenuStripBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color GridHeaderCellColor {
            get {
                return ((global::System.Drawing.Color)(this["GridHeaderCellColor"]));
            }
            set {
                this["GridHeaderCellColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color SurfaceBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["SurfaceBorderColor"]));
            }
            set {
                this["SurfaceBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public global::Salem.Drawing.ColorModes TitleBarColorMode {
            get {
                return ((global::Salem.Drawing.ColorModes)(this["TitleBarColorMode"]));
            }
            set {
                this["TitleBarColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InactiveCaption")]
        public global::System.Drawing.Color GridHeaderCellHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["GridHeaderCellHighlightColor"]));
            }
            set {
                this["GridHeaderCellHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color SurfaceHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["SurfaceHoverColor"]));
            }
            set {
                this["SurfaceHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("216, 216, 216")]
        public global::System.Drawing.Color InactiveTabBackColor {
            get {
                return ((global::System.Drawing.Color)(this["InactiveTabBackColor"]));
            }
            set {
                this["InactiveTabBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2016Colorful")]
        public global::Syncfusion.Windows.Forms.VisualStyle DateTimePickerStyle {
            get {
                return ((global::Syncfusion.Windows.Forms.VisualStyle)(this["DateTimePickerStyle"]));
            }
            set {
                this["DateTimePickerStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2016White")]
        public global::Syncfusion.Windows.Forms.Tools.TextBoxExt.theme SyncTextBoxStyle {
            get {
                return ((global::Syncfusion.Windows.Forms.Tools.TextBoxExt.theme)(this["SyncTextBoxStyle"]));
            }
            set {
                this["SyncTextBoxStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 120, 215")]
        public global::System.Drawing.Color MenuStripItemBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripItemBorderColor"]));
            }
            set {
                this["MenuStripItemBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("179, 215, 243")]
        public global::System.Drawing.Color MenuStripItemHoverBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripItemHoverBackColor"]));
            }
            set {
                this["MenuStripItemHoverBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public global::DVLD_Business.SupportedLanguages CurrentLanguage {
            get {
                return ((global::DVLD_Business.SupportedLanguages)(this["CurrentLanguage"]));
            }
            set {
                this["CurrentLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberedUsername {
            get {
                return ((string)(this["RememberedUsername"]));
            }
            set {
                this["RememberedUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberedPassword {
            get {
                return ((string)(this["RememberedPassword"]));
            }
            set {
                this["RememberedPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CurrentThemeID {
            get {
                return ((int)(this["CurrentThemeID"]));
            }
            set {
                this["CurrentThemeID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public global::Salem.Drawing.ColorModes CurrentThemeColorMode {
            get {
                return ((global::Salem.Drawing.ColorModes)(this["CurrentThemeColorMode"]));
            }
            set {
                this["CurrentThemeColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color SurfaceBackColor {
            get {
                return ((global::System.Drawing.Color)(this["SurfaceBackColor"]));
            }
            set {
                this["SurfaceBackColor"] = value;
            }
        }
    }
}
