//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD_Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD_Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart has been saved successfully.
        ///Click here to see it..
        /// </summary>
        internal static string chartExportedSuccessfully {
            get {
                return ResourceManager.GetString("chartExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been saved successfully.
        ///Click here to see it..
        /// </summary>
        internal static string dataExportedSuccessfully {
            get {
                return ResourceManager.GetString("dataExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while exporting the data.
        ///Please try again..
        /// </summary>
        internal static string dataExportFailed {
            get {
                return ResourceManager.GetString("dataExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DVLD_Icon {
            get {
                object obj = ResourceManager.GetObject("DVLD Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DVLD_Logo {
            get {
                object obj = ResourceManager.GetObject("DVLD Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DVLD_Logo_Grayscale {
            get {
                object obj = ResourceManager.GetObject("DVLD Logo Grayscale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees Sammary.
        /// </summary>
        internal static string feesSammary {
            get {
                return ResourceManager.GetString("feesSammary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAND TOTAL.
        /// </summary>
        internal static string grandTotal {
            get {
                return ResourceManager.GetString("grandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time.
        /// </summary>
        internal static string issueNewLicense {
            get {
                return ResourceManager.GetString("issueNewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available....
        /// </summary>
        internal static string noDataAvailable {
            get {
                return ResourceManager.GetString("noDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not Set&gt;.
        /// </summary>
        internal static string notSetField {
            get {
                return ResourceManager.GetString("notSetField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string orderNum {
            get {
                return ResourceManager.GetString("orderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal.
        /// </summary>
        internal static string renewal {
            get {
                return ResourceManager.GetString("renewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement for Damaged.
        /// </summary>
        internal static string replacementForDamaged {
            get {
                return ResourceManager.GetString("replacementForDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement for Lost.
        /// </summary>
        internal static string replacementForLost {
            get {
                return ResourceManager.GetString("replacementForLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by the DVLD project created by Abdulrahman Mohammad Salem, supervised by ProgrammingAdvices.com.
        /// </summary>
        internal static string reportAuthor {
            get {
                return ResourceManager.GetString("reportAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string unexpectedError {
            get {
                return ResourceManager.GetString("unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
