//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD_DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD_DataAccess.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string app_cancelled {
            get {
                return ResourceManager.GetString("app_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string app_completed {
            get {
                return ResourceManager.GetString("app_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string app_new {
            get {
                return ResourceManager.GetString("app_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detentions.
        /// </summary>
        internal static string detentions {
            get {
                return ResourceManager.GetString("detentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Creation.
        /// </summary>
        internal static string field_applicationsCreated {
            get {
                return ResourceManager.GetString("field_applicationsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Creation.
        /// </summary>
        internal static string field_driversCreated {
            get {
                return ResourceManager.GetString("field_driversCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Detention Operation.
        /// </summary>
        internal static string field_licenseDetentionOperations {
            get {
                return ResourceManager.GetString("field_licenseDetentionOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Creation.
        /// </summary>
        internal static string field_licensesCreated {
            get {
                return ResourceManager.GetString("field_licensesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Appointment Creation.
        /// </summary>
        internal static string field_testAppointsCreated {
            get {
                return ResourceManager.GetString("field_testAppointsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result Saving.
        /// </summary>
        internal static string field_testResultsCreated {
            get {
                return ResourceManager.GetString("field_testResultsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International License.
        /// </summary>
        internal static string interLicense {
            get {
                return ResourceManager.GetString("interLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string releases {
            get {
                return ResourceManager.GetString("releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal.
        /// </summary>
        internal static string renewal {
            get {
                return ResourceManager.GetString("renewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement for Damaged.
        /// </summary>
        internal static string replacementForDamaged {
            get {
                return ResourceManager.GetString("replacementForDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement for Lost.
        /// </summary>
        internal static string replacementForLost {
            get {
                return ResourceManager.GetString("replacementForLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
