//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Layouts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_LayoutManageDetainedLicenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_LayoutManageDetainedLicenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Layouts.Str_LayoutManageDetainedLicenses", typeof(Str_LayoutManageDetainedLicenses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detain Date.
        /// </summary>
        internal static string detainDate {
            get {
                return ResourceManager.GetString("detainDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detained Licenses.
        /// </summary>
        internal static string detainedLicenses {
            get {
                return ResourceManager.GetString("detainedLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detain ID.
        /// </summary>
        internal static string detainID {
            get {
                return ResourceManager.GetString("detainID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Fees.
        /// </summary>
        internal static string fineFees {
            get {
                return ResourceManager.GetString("fineFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Released?.
        /// </summary>
        internal static string isReleased {
            get {
                return ResourceManager.GetString("isReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local License ID.
        /// </summary>
        internal static string localLicenseID {
            get {
                return ResourceManager.GetString("localLicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release App. ID.
        /// </summary>
        internal static string releaseAppID {
            get {
                return ResourceManager.GetString("releaseAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string releaseDate {
            get {
                return ResourceManager.GetString("releaseDate", resourceCulture);
            }
        }
    }
}
