//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD.String_Resources.Layouts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_LayoutManageInternationalDrivingLicenseApps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_LayoutManageInternationalDrivingLicenseApps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD.String_Resources.Layouts.Str_LayoutManageInternationalDrivingLicenseApps", typeof(Str_LayoutManageInternationalDrivingLicenseApps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        internal static string applicationID {
            get {
                return ResourceManager.GetString("applicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string expirationDate {
            get {
                return ResourceManager.GetString("expirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Driving License Applications.
        /// </summary>
        internal static string interDrivingLicenseApps {
            get {
                return ResourceManager.GetString("interDrivingLicenseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int. License ID.
        /// </summary>
        internal static string interLicenseID {
            get {
                return ResourceManager.GetString("interLicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        internal static string issueDate {
            get {
                return ResourceManager.GetString("issueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L. License ID.
        /// </summary>
        internal static string localLicenseID {
            get {
                return ResourceManager.GetString("localLicenseID", resourceCulture);
            }
        }
    }
}
