//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD_Business.Report_Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_UserActivityReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_UserActivityReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD_Business.Report_Strings.Str_UserActivityReport", typeof(Str_UserActivityReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION CREATIONS.
        /// </summary>
        internal static string applicationCreations {
            get {
                return ResourceManager.GetString("applicationCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string cap_description {
            get {
                return ResourceManager.GetString("cap_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity ID.
        /// </summary>
        internal static string cap_entityID {
            get {
                return ResourceManager.GetString("cap_entityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        internal static string cap_entityType {
            get {
                return ResourceManager.GetString("cap_entityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Information.
        /// </summary>
        internal static string cap_loginInfo {
            get {
                return ResourceManager.GetString("cap_loginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        internal static string cap_specification {
            get {
                return ResourceManager.GetString("cap_specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string col_action {
            get {
                return ResourceManager.GetString("col_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string col_count {
            get {
                return ResourceManager.GetString("col_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVER CREATIONS (PER NATIONALITY).
        /// </summary>
        internal static string driverCreations_perNationality {
            get {
                return ResourceManager.GetString("driverCreations_perNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        internal static string field_isActive {
            get {
                return ResourceManager.GetString("field_isActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string field_userID {
            get {
                return ResourceManager.GetString("field_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string field_username {
            get {
                return ResourceManager.GetString("field_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Timeline.
        /// </summary>
        internal static string h_activityTimeline {
            get {
                return ResourceManager.GetString("h_activityTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Action Counts.
        /// </summary>
        internal static string h_basicActionCounts {
            get {
                return ResourceManager.GetString("h_basicActionCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorized Activities.
        /// </summary>
        internal static string h_categorizedActivities {
            get {
                return ResourceManager.GetString("h_categorizedActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Action Counts.
        /// </summary>
        internal static string h_detailedActionCounts {
            get {
                return ResourceManager.GetString("h_detailedActionCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        internal static string h_userInfo {
            get {
                return ResourceManager.GetString("h_userInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNATIONAL LICENSE CREATIONS.
        /// </summary>
        internal static string internationalLicenseCreations {
            get {
                return ResourceManager.GetString("internationalLicenseCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE DETENTION OPERATIONS.
        /// </summary>
        internal static string licenseDetentionOperations {
            get {
                return ResourceManager.GetString("licenseDetentionOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL LICENSE CREATIONS.
        /// </summary>
        internal static string localLicenseCreations {
            get {
                return ResourceManager.GetString("localLicenseCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A report documenting the activities and transactions done by the user of the ID .
        /// </summary>
        internal static string reportSubject_1 {
            get {
                return ResourceManager.GetString("reportSubject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activity Report.
        /// </summary>
        internal static string reportTitle {
            get {
                return ResourceManager.GetString("reportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST APPOINTMENT CREATIONS.
        /// </summary>
        internal static string testAppointmentCreations {
            get {
                return ResourceManager.GetString("testAppointmentCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST RESULT CREATIONS.
        /// </summary>
        internal static string testResultsCreations {
            get {
                return ResourceManager.GetString("testResultsCreations", resourceCulture);
            }
        }
    }
}
