//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD_Business.Report_Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_LDLAppDetailsReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_LDLAppDetailsReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD_Business.Report_Strings.Str_LDLAppDetailsReport", typeof(Str_LDLAppDetailsReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Basic Info.
        /// </summary>
        internal static string cap_appBasicInfo {
            get {
                return ResourceManager.GetString("cap_appBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving License Application Info.
        /// </summary>
        internal static string cap_drivingLicenseAppInfo {
            get {
                return ResourceManager.GetString("cap_drivingLicenseAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string classAbbr {
            get {
                return ResourceManager.GetString("classAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string col_amount {
            get {
                return ResourceManager.GetString("col_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Unit Price.
        /// </summary>
        internal static string col_avgUnitPrice {
            get {
                return ResourceManager.GetString("col_avgUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string col_product {
            get {
                return ResourceManager.GetString("col_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint. ID.
        /// </summary>
        internal static string col_testAppointID {
            get {
                return ResourceManager.GetString("col_testAppointID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string col_total {
            get {
                return ResourceManager.GetString("col_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid Fees.
        /// </summary>
        internal static string col_totalPaidFees {
            get {
                return ResourceManager.GetString("col_totalPaidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Test Appoint..
        /// </summary>
        internal static string drivingTestAppoint {
            get {
                return ResourceManager.GetString("drivingTestAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Name.
        /// </summary>
        internal static string field_applicantName {
            get {
                return ResourceManager.GetString("field_applicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Date.
        /// </summary>
        internal static string field_applicationDate {
            get {
                return ResourceManager.GetString("field_applicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied For License.
        /// </summary>
        internal static string field_appliedForLicense {
            get {
                return ResourceManager.GetString("field_appliedForLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Type.
        /// </summary>
        internal static string field_appType {
            get {
                return ResourceManager.GetString("field_appType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Application ID.
        /// </summary>
        internal static string field_baseAppID {
            get {
                return ResourceManager.GetString("field_baseAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string field_fees {
            get {
                return ResourceManager.GetString("field_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.D.L.App. ID.
        /// </summary>
        internal static string field_localDrivingLicenseAppID {
            get {
                return ResourceManager.GetString("field_localDrivingLicenseAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Passed Tests.
        /// </summary>
        internal static string field_numPassedTests {
            get {
                return ResourceManager.GetString("field_numPassedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string field_status {
            get {
                return ResourceManager.GetString("field_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Update Date.
        /// </summary>
        internal static string field_statusUpdateDate {
            get {
                return ResourceManager.GetString("field_statusUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Info.
        /// </summary>
        internal static string h_applicantInfo {
            get {
                return ResourceManager.GetString("h_applicantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Info.
        /// </summary>
        internal static string h_applicationInfo {
            get {
                return ResourceManager.GetString("h_applicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Test Appointments.
        /// </summary>
        internal static string h_drivingTestAppoints {
            get {
                return ResourceManager.GetString("h_drivingTestAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Info.
        /// </summary>
        internal static string h_testInfo {
            get {
                return ResourceManager.GetString("h_testInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Test Appointments.
        /// </summary>
        internal static string h_visionTestAppoints {
            get {
                return ResourceManager.GetString("h_visionTestAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Test Appointments.
        /// </summary>
        internal static string h_writtenTestAppoints {
            get {
                return ResourceManager.GetString("h_writtenTestAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Class.
        /// </summary>
        internal static string licenseClass {
            get {
                return ResourceManager.GetString("licenseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.D.L. Application.
        /// </summary>
        internal static string localLicenseApp {
            get {
                return ResourceManager.GetString("localLicenseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A report documenting the details of a local driving license application with the ID of .
        /// </summary>
        internal static string reportSubject_1 {
            get {
                return ResourceManager.GetString("reportSubject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.L.App. Details Report.
        /// </summary>
        internal static string reportTitle {
            get {
                return ResourceManager.GetString("reportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake Test Application.
        /// </summary>
        internal static string retakeTestApp {
            get {
                return ResourceManager.GetString("retakeTestApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Test Appoint..
        /// </summary>
        internal static string visionTestAppoint {
            get {
                return ResourceManager.GetString("visionTestAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Test Appoint..
        /// </summary>
        internal static string writtenTestAppoint {
            get {
                return ResourceManager.GetString("writtenTestAppoint", resourceCulture);
            }
        }
    }
}
