//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVLD_Business.Report_Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_PersonHistoryReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_PersonHistoryReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVLD_Business.Report_Strings.Str_PersonHistoryReport", typeof(Str_PersonHistoryReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        internal static string allTime {
            get {
                return ResourceManager.GetString("allTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App. ID.
        /// </summary>
        internal static string col_appID {
            get {
                return ResourceManager.GetString("col_appID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint. Created By.
        /// </summary>
        internal static string col_appointCreatedBy {
            get {
                return ResourceManager.GetString("col_appointCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint. Date.
        /// </summary>
        internal static string col_appointDate {
            get {
                return ResourceManager.GetString("col_appointDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assoc.L. License ID.
        /// </summary>
        internal static string col_assocLocalLicenseID {
            get {
                return ResourceManager.GetString("col_assocLocalLicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string col_class {
            get {
                return ResourceManager.GetString("col_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string col_createdBy {
            get {
                return ResourceManager.GetString("col_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string col_dateTime {
            get {
                return ResourceManager.GetString("col_dateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detain Date.
        /// </summary>
        internal static string col_detainDate {
            get {
                return ResourceManager.GetString("col_detainDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detain Reason.
        /// </summary>
        internal static string col_detainReason {
            get {
                return ResourceManager.GetString("col_detainReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string col_expirationDate {
            get {
                return ResourceManager.GetString("col_expirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string col_fees {
            get {
                return ResourceManager.GetString("col_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Fees.
        /// </summary>
        internal static string col_fineFees {
            get {
                return ResourceManager.GetString("col_fineFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Fees.
        /// </summary>
        internal static string col_firstTimeFees {
            get {
                return ResourceManager.GetString("col_firstTimeFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string col_id {
            get {
                return ResourceManager.GetString("col_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        internal static string col_isActive {
            get {
                return ResourceManager.GetString("col_isActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Locked?.
        /// </summary>
        internal static string col_isLocked {
            get {
                return ResourceManager.GetString("col_isLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Released?.
        /// </summary>
        internal static string col_isReleased {
            get {
                return ResourceManager.GetString("col_isReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        internal static string col_issueDate {
            get {
                return ResourceManager.GetString("col_issueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Notes.
        /// </summary>
        internal static string col_issueNotes {
            get {
                return ResourceManager.GetString("col_issueNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Reason.
        /// </summary>
        internal static string col_issueReason {
            get {
                return ResourceManager.GetString("col_issueReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.L.App. ID.
        /// </summary>
        internal static string col_localLicenseAppID {
            get {
                return ResourceManager.GetString("col_localLicenseAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local License ID.
        /// </summary>
        internal static string col_localLicenseID {
            get {
                return ResourceManager.GetString("col_localLicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Fees.
        /// </summary>
        internal static string col_paidFees {
            get {
                return ResourceManager.GetString("col_paidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed Tests.
        /// </summary>
        internal static string col_passedTests {
            get {
                return ResourceManager.GetString("col_passedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release App. ID.
        /// </summary>
        internal static string col_releaseAppID {
            get {
                return ResourceManager.GetString("col_releaseAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string col_releaseDate {
            get {
                return ResourceManager.GetString("col_releaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released By.
        /// </summary>
        internal static string col_releasedBy {
            get {
                return ResourceManager.GetString("col_releasedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake App. ID.
        /// </summary>
        internal static string col_retakeAppID {
            get {
                return ResourceManager.GetString("col_retakeAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string col_status {
            get {
                return ResourceManager.GetString("col_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint. ID.
        /// </summary>
        internal static string col_testAppointID {
            get {
                return ResourceManager.GetString("col_testAppointID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Created By.
        /// </summary>
        internal static string col_testCreatedBy {
            get {
                return ResourceManager.GetString("col_testCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        internal static string col_testResult {
            get {
                return ResourceManager.GetString("col_testResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid Fees.
        /// </summary>
        internal static string col_totalPaidFees {
            get {
                return ResourceManager.GetString("col_totalPaidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string col_type {
            get {
                return ResourceManager.GetString("col_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        internal static string col_updateDate {
            get {
                return ResourceManager.GetString("col_updateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string field_address {
            get {
                return ResourceManager.GetString("field_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string field_dateOfBirth {
            get {
                return ResourceManager.GetString("field_dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string field_email {
            get {
                return ResourceManager.GetString("field_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string field_fullName {
            get {
                return ResourceManager.GetString("field_fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string field_gender {
            get {
                return ResourceManager.GetString("field_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string field_nationality {
            get {
                return ResourceManager.GetString("field_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National No.
        /// </summary>
        internal static string field_nationalNum {
            get {
                return ResourceManager.GetString("field_nationalNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person ID.
        /// </summary>
        internal static string field_personID {
            get {
                return ResourceManager.GetString("field_personID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        internal static string field_phoneNum {
            get {
                return ResourceManager.GetString("field_phoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string h_apps {
            get {
                return ResourceManager.GetString("h_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detentions.
        /// </summary>
        internal static string h_detentions {
            get {
                return ResourceManager.GetString("h_detentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Tests.
        /// </summary>
        internal static string h_drivingTests {
            get {
                return ResourceManager.GetString("h_drivingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Licenses.
        /// </summary>
        internal static string h_interLicenses {
            get {
                return ResourceManager.GetString("h_interLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local License Applications.
        /// </summary>
        internal static string h_localLicenseApps {
            get {
                return ResourceManager.GetString("h_localLicenseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Licenses.
        /// </summary>
        internal static string h_localLicenses {
            get {
                return ResourceManager.GetString("h_localLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Applications.
        /// </summary>
        internal static string h_otherApps {
            get {
                return ResourceManager.GetString("h_otherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        internal static string h_personalInfo {
            get {
                return ResourceManager.GetString("h_personalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string h_tests {
            get {
                return ResourceManager.GetString("h_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Tests.
        /// </summary>
        internal static string h_visionTests {
            get {
                return ResourceManager.GetString("h_visionTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Tests.
        /// </summary>
        internal static string h_writtenTests {
            get {
                return ResourceManager.GetString("h_writtenTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A report documenting the history of a person with the ID of .
        /// </summary>
        internal static string reportSubject_1 {
            get {
                return ResourceManager.GetString("reportSubject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and the national number of .
        /// </summary>
        internal static string reportSubject_2 {
            get {
                return ResourceManager.GetString("reportSubject_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person History Report.
        /// </summary>
        internal static string reportTitle {
            get {
                return ResourceManager.GetString("reportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PAID FINE FEES.
        /// </summary>
        internal static string totalPaidFineFees {
            get {
                return ResourceManager.GetString("totalPaidFineFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PENDING FINE FEES.
        /// </summary>
        internal static string totalPendingFineFees {
            get {
                return ResourceManager.GetString("totalPendingFineFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Until.
        /// </summary>
        internal static string upUntil {
            get {
                return ResourceManager.GetString("upUntil", resourceCulture);
            }
        }
    }
}
